package com.phantomclone.data.model

import kotlinx.serialization.Serializable

/**
 * Proxy type options available per profile.
 */
@Serializable
enum class ProxyType {
    NONE,
    HTTP,
    SOCKS5
}

/**
 * Proxy configuration for a profile.
 *
 * @property type The type of proxy to use.
 * @property host Proxy server hostname or IP.
 * @property port Proxy server port.
 * @property username Optional authentication username.
 * @property password Optional authentication password.
 */
@Serializable
data class ProxyConfig(
    val type: ProxyType = ProxyType.NONE,
    val host: String = "",
    val port: Int = 0,
    val username: String = "",
    val password: String = ""
)

/**
 * Comprehensive device fingerprint data produced by [FingerprintGenerator][com.phantomclone.fingerprint.FingerprintGenerator].
 *
 * All fields are designed to be internally consistent — e.g., a Samsung Galaxy S24
 * will have Samsung as manufacturer, matching GPU, resolution, etc.
 *
 * @property manufacturer Device manufacturer (e.g., "Samsung").
 * @property brand Device brand (e.g., "samsung").
 * @property model Device model (e.g., "SM-S928B").
 * @property product Product name (e.g., "galaxy_s24").
 * @property hardware Hardware name (e.g., "qcom").
 * @property board Board name (e.g., "msm8998").
 * @property buildFingerprint Full build fingerprint string.
 * @property buildDisplay Build display string.
 * @property androidVersion Android version name (e.g., "14").
 * @property sdkInt Android SDK version integer.
 * @property cpuAbi Primary CPU ABI (e.g., "arm64-v8a").
 * @property cpuAbi2 Secondary CPU ABI.
 * @property screenWidth Screen width in pixels.
 * @property screenHeight Screen height in pixels.
 * @property dpi Screen density in DPI.
 * @property androidId Spoofed ANDROID_ID (16-char hex).
 * @property googleAdId Spoofed Google Advertising ID (UUID format).
 * @property wifiMac Spoofed WiFi MAC address (XX:XX:XX:XX:XX:XX).
 * @property imei Spoofed IMEI number (15 digits, Luhn-valid).
 * @property phoneNumber Spoofed phone number.
 * @property carrier Network carrier name.
 * @property timezone Device timezone (e.g., "America/New_York").
 * @property locale Device locale (e.g., "en_US").
 * @property language Device language code (e.g., "en").
 * @property userAgent WebView user-agent string.
 * @property glRenderer OpenGL renderer string.
 * @property glVendor OpenGL vendor string.
 * @property sensors List of sensor names available on the device.
 * @property serial Build serial number.
 */
@Serializable
data class DeviceFingerprint(
    val manufacturer: String = "",
    val brand: String = "",
    val model: String = "",
    val product: String = "",
    val hardware: String = "",
    val board: String = "",
    val buildFingerprint: String = "",
    val buildDisplay: String = "",
    val androidVersion: String = "",
    val sdkInt: Int = 0,
    val cpuAbi: String = "",
    val cpuAbi2: String = "",
    val screenWidth: Int = 0,
    val screenHeight: Int = 0,
    val dpi: Int = 0,
    val androidId: String = "",
    val googleAdId: String = "",
    val wifiMac: String = "",
    val imei: String = "",
    val phoneNumber: String = "",
    val carrier: String = "",
    val timezone: String = "",
    val locale: String = "",
    val language: String = "",
    val userAgent: String = "",
    val glRenderer: String = "",
    val glVendor: String = "",
    val sensors: List<String> = emptyList(),
    val serial: String = ""
)

/**
 * A single PhantomClone profile managed by the user.
 *
 * @property id Unique identifier (auto-generated by Room).
 * @property name User-defined profile name.
 * @property fingerprint The [DeviceFingerprint] associated with this profile.
 * @property proxyConfig Proxy configuration for this profile.
 * @property notes Optional user notes.
 * @property createdAt Creation timestamp in millis.
 * @property lastUsedAt Last-used timestamp in millis, or null if never used.
 * @property isActive Whether the profile is currently active/running.
 */
@Serializable
data class Profile(
    val id: Long = 0,
    val name: String = "",
    val fingerprint: DeviceFingerprint = DeviceFingerprint(),
    val proxyConfig: ProxyConfig = ProxyConfig(),
    val notes: String = "",
    val createdAt: Long = System.currentTimeMillis(),
    val lastUsedAt: Long? = null,
    val isActive: Boolean = false
)

/**
 * Represents an app installed inside a virtual profile.
 *
 * @property packageName Package name of the cloned app.
 * @property appName User-visible app name.
 * @property apkPath Path to the APK inside the sandbox directory.
 * @property profileId The ID of the profile this app belongs to.
 * @property installedAt Installation timestamp in millis.
 * @property versionName App version name.
 * @property versionCode App version code.
 */
@Serializable
data class InstalledApp(
    val packageName: String = "",
    val appName: String = "",
    val apkPath: String = "",
    val profileId: Long = 0,
    val installedAt: Long = System.currentTimeMillis(),
    val versionName: String = "",
    val versionCode: Long = 0
)
